# mybatis
mybatis:
  mapper-locations: classpath*:org/semlab/xml/*.xml
  type-aliases-package: org.semlab.model
  type-handlers-package: org.semlab.typehandler

# pagehelper
pagehelper:
  helperDialect: postgresql #mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql