# Spring主配置文件
# yaml格式配置文件
# 键值之间需要有一个空格

# profies：dev  application-dev.yml
#          prod application-prod.yml
spring:
  profiles:
    active: dev
  #jackson:
    #default-property-inclusion: non_null
# druid pool
  datasource:
    initial-size: 3
    max-active: 10
    min-idle: 2
    max-wait: 3000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 50
    filters:
      - stat
      - wall # 'wall'用于防火墙
      - slf4j
    log-abandoned: true

  ## Freemarker 配置
  ## 文件配置路径
  freemarker:
    template-loader-path: classpath:/ftl/
    cache: false #在不重启容器的情况下重新加载FreeMarker模板
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

# mybatis
mybatis:
  mapper-locations: classpath*:org/semlab/mapper/*.xml
  type-aliases-package: org.semlab.model
  type-handlers-package: org.semlab.typehandler

# pagehelper
pagehelper:
    helper-dialect: postgresql #mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

# druid 监控
druid:
  user: admin
  psd: db123
  resetEnable: false

cxf:
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger
