# development profile
# 开发环境，根据自己的开发环境进行配置

# Server
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 60
  contextPath: /app

# Logging
logging:
  level:
    root: DEBUG

# DataSource
spring:
  datasource:
    # database
    master-db:
      url: jdbc:postgresql://localhost:5432/semtest #jdbc:mysql://localhost/test
      username: gdo
      password: geo_ont
      driver-class-name: org.postgresql.Driver # com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #schema: classpath:db.sql
    cluster-db:
      url: jdbc:postgresql://localhost/test #jdbc:mysql://localhost/test
      username: dblab
      password: admin
      driver-class-name: org.postgresql.Driver # com.mysql.jdbc.Driver

# Jena config
jena:
  tdb:
    assembler: classpath:/ont-config/assembler.ttl
    dbLocation: H:/OntoBase/egc/tdb
    location-mapping: classpath:/ont-config/location-mapping.ttl
  jdbc:
  # https://github.com/apache/jena/tree/master/jena-jdbc
    mem:
    # Sets a dataset file to load in as the initial dataset, this or the empty parameter must be provided
    #  dataset:
      empty: true
    tdb:
      must-exist: false
    # remote:
    #   baseURL:
    #   query: true
    #   update: true
    #   named-graph-uri:
    #   using-graph-uri:
    #   using-named-graph-uri:
    #   user:
    #   password:
    #   select-results-type: application/sparql-results+mapper
    #   model-results-type: text/turtle
  inf:
    rules: classpath:/ont-config/reasoner.rules