# DataSource
datasource:
  db-my:
    url: jdbc:postgresql://localhost:5432/semtest #jdbc:mysql://localhost/test
    username: gdo
    password: geo_ont
    driver-class-name: org.postgresql.Driver # com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #schema: classpath:db.sql
  db-server:
    url: jdbc:postgresql://localhost/test #jdbc:mysql://localhost/test
    username: dblab
    password: admin
    driver-class-name: org.postgresql.Driver # com.mysql.jdbc.Driver