# 废弃：
#   配置转移到主配置文件 application.yml中
# mybatis
mybatis:
  mapper-locations: classpath*:org/semlab/mapper/*.mapper
  type-aliases-package: org.semlab.model
  type-handlers-package: org.semlab.typehandler
  # pagehelper
  helper-dialect: postgresql #mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql